version: '3.1'

services:

  datalytics-app:
    build: .
    ports:
      - "80:8080"
    environment:
      DB_PASSWORD: db_password
      PGUSER: db_username
      DB_URL: "jdbc:postgresql://capibytes-db.cmw2whm4hmzl.us-east-1.rds.amazonaws.com:5432/postgres"